### ISSUE TITLE
Review vue sidebar and create list of new features for sidebar.

### ISSUE THREAD

**Issue by wildone** [typerefinery-ai/typerefinery-websight#198]
Review this and come up with list of additional features.

<img width="307" alt="image" src="https://user-images.githubusercontent.com/170312/223939212-57b24003-04da-4fc6-8afa-304994bc792f.png">

**Comment by Rahul139-stack** [comment]
Additional Feature List

- [ ] On click every  sidebar tree node ,new tab will open for the particular node  
```
