### ISSUE TITLE
Create new Tab Container

### ISSUE THREAD

**Issue by wildone** [typerefinery-ai/typerefinery-websight#199]
Able to:
- [x] Author tabs
- [x] #268
- [x] Load urls or content 
- [x] Need an option to pass query string/data from parent page to iframe page, this will be used on Forms that appear in Modals, they will pass their query string to the sub sequent forms.
- [x] #263
- [ ] #264 
- [x] #269

Need to be able to replicate similar functionality as this:

<img width="211" alt="image" src="https://user-images.githubusercontent.com/170312/225210025-158ec6fd-6d91-4bda-9ddc-e8be1fc77419.png">

<img width="154" alt="image" src="https://user-images.githubusercontent.com/170312/225210095-507876a8-4236-4dc6-8114-52b387b634da.png">

<img width="464" alt="image" src="https://user-images.githubusercontent.com/170312/225210118-7cf07b84-ce34-4eeb-bc86-d4a8ed43f704.png">

**Comment by Harikarthyk** [comment]
Completed
