### ISSUE TITLE
Create base docs for all components.

### ISSUE THREAD

**Issue by wildone** [typerefinery-ai/typerefinery-websight#200]
Lets create a README.md in each component folder.

Reference Example:
- https://github.com/aem-design/aemdesign-aem-core/blob/4ea50b8db6ffd822be24c12a042d3a13290aaedd/aemdesign-aem-common/src/main/content/jcr_root/apps/aemdesign/components/content/text/v2/text/README.md

TOC:

- [x] Properties - info .content.json
- [x] Configuration  - dialog fields and examples
- [x] Examples
- [x] Theme Documentation

**Comment by Rahul139-stack** [comment]
> Lets create a README.md in each component folder.
> 
> Reference Example:
> 
> * https://github.com/aem-design/aemdesign-aem-core/blob/4ea50b8db6ffd822be24c12a042d3a13290aaedd/aemdesign-aem-common/src/main/content/jcr_root/apps/aemdesign/components/content/text/v2/text/README.md
> 
> TOC:
> 
> * [x]  Properties - info .content.json
> * [x]  Configuration  - dialog fields and examples
> * [x]  Examples
> * [ ]  Theme Documentation

Docs for Map component completed.
