### ISSUE TITLE
Update form select to allow simpler selection of multiple items

### ISSUE THREAD

**Issue by wildone** [typerefinery-ai/typerefinery-websight#224]
Need to be able to have easy way to select multiple items in a form drowpdown.

<img width="289" alt="image" src="https://user-images.githubusercontent.com/170312/225534447-553fd405-07ec-451f-9421-9c290da069f3.png">

https://mdbootstrap.com/docs/standard/extended/multiselect/

**Comment by Harikarthyk** [comment]
Completed
