### ISSUE TITLE
Create Container Menu component

### ISSUE THREAD

**Issue by wildone** [typerefinery-ai/typerefinery-websight#265]
This component will create a menu from sibling containers.

- Default behaviour, Sibling containers are all immediate children of the parent.
- Pick a path of parent to look for children.

This component will provide a way to make a TOC or a scroll menu.

**Comment by Harikarthyk** [comment]
Reference: https://codepen.io/zbymhz/pen/ExjRNwZ

**Comment by Harikarthyk** [comment]
Completed 
Author - @Rahul139-stack
