### ISSUE TITLE
Update form to enable JSON Payload Type to store files in a blobstore service.

### ISSUE THREAD

**Issue by wildone** [typerefinery-ai/typerefinery-websight#276]
Need to be able to save files to blobstore service and then send URL's in payload.

Depandant: https://github.com/typerefinery-ai/typerefinery/issues/459

**Comment by Harikarthyk** [comment]
1. Save the file to the blob store and pass the result to the Endpoint.
    - [ ] Create a structure for putting the files. (/path_to_form/GUID/file_name.mimetype)
    - [ ] Click on submit should wait until the files are uploaded.
    - [ ] When the files are uploading, some kind of indication or progress bar for the files should be visible and then once the files are upload, then link to view the file should be added.
    - [ ] Allow drag and drop option accept files. 
    - [ ] Allow option to remove the files added.
    
    
2. Update the flow to save file payload to the blob store

**Comment by Harikarthyk** [comment]
Completed
