### ISSUE TITLE
New Project Does not load in New Version of Old UI

### ISSUE THREAD

**Issue by brettforbes** [typerefinery-ai/typerefinery-websight#282]
**Describe the bug**
Starting the new UI with the new version of the TypeDB query system, and then pressing the New Project button, means the new project will not save

**To Reproduce**
1. Start the version of the UI with the TypeDB query Experience
2. Select New Project button
3. Select Default as Project Type, and Global Query, Global Connection, and Global Theme
4. Press "Save" button
5. Project will never save and never exit this window
<img width="948" alt="image" src="https://user-images.githubusercontent.com/24556510/230752638-0be97a5b-21c5-40b0-864e-b70cea3e8c1b.png">

**Expected behavior**
The Project should save quickly, and the default project should be loaded

**Screenshots**
<img width="948" alt="image" src="https://user-images.githubusercontent.com/24556510/230752652-58e94c7d-4ae7-4098-ac6a-acfaf1f2ce87.png">

**Desktop (please complete the following information):**
- Windows 11, using Electron app

**Additional context**
nil

**Comment by Harikarthyk** [comment]
Completed
