### ISSUE TITLE
When Choosing to Add Existing Experiences, the Blank Screen problem arises and is never resolved

### ISSUE THREAD

**Issue by brettforbes** [typerefinery-ai/typerefinery-websight#283]
**Describe the bug**
Once the button to add an existing experience is selected from the services tab, the blank screen problem arises, and never resolves

**To Reproduce**
1. Load the Electron App with the new version of the TypeDB query system
2. Go to the settings, and press the buttons to select the existing experiences listed, Dashboard, Chart, Map etc
3. Exit settings and the Blank Screen problem arises and is never resolved

**Expected behavior**
1. Never, ever show the Blank screen with the gray bands, never, ever
2. Provide an overlay screen, with a progress bar and access to documentation until new experiences loaded
3. Provide access to the new experiences

**Screenshots**
<img width="1034" alt="image" src="https://user-images.githubusercontent.com/24556510/230752810-402f3e5b-0c4f-4246-b9c6-110cd9bfe92c.png">

**Desktop (please complete the following information):**
- Windows 11

**Additional context**
nil

**Comment by Rahul139-stack** [comment]
> **Describe the bug** Once the button to add an existing experience is selected from the services tab, the blank screen problem arises, and never resolves
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Load the Electron App with the new version of the TypeDB query system
> 2. Go to the settings, and press the buttons to select the existing experiences listed, Dashboard, Chart, Map etc
> 3. Exit settings and the Blank Screen problem arises and is never resolved
> 
> **Expected behavior**
> 
> 1. Never, ever show the Blank screen with the gray bands, never, ever
> 2. Provide an overlay screen, with a progress bar and access to documentation until new experiences loaded
> 3. Provide access to the new experiences
> 
> **Screenshots** <img alt="image" width="1034" src="https://user-images.githubusercontent.com/24556510/230752810-402f3e5b-0c4f-4246-b9c6-110cd9bfe92c.png">
> 
> **Desktop (please complete the following information):**
> 
> * Windows 11
> 
> **Additional context** nil

@brettforbes ,please the new typeDB query.

**Comment by Rahul139-stack** [comment]
Resolved
