### ISSUE TITLE
Add new client side feature to draw small icon on widgets that have flow enabled.

### ISSUE THREAD

**Issue by wildone** [typerefinery-ai/typerefinery-websight#286]
We need a quick way to jump to flow editing when you are viewing experience.

Need a small and subtle icon top right of the component with a link to the `flowapi_editurl`.

Here is an example https://codepen.io/maxbarrass/pen/eYPWXoW

Status icon
- [x] All component that support flow whould have a grayed out icon. This will allow to see all components that have flow capabilities.
- [x] All component that have flow enable should have a colored icon and has a `flowapi_editurl` link. This will allow to jump to editing of the flow quickly.
- no icon for other components

<img width="72" alt="image" src="https://user-images.githubusercontent.com/170312/234712955-31a55020-4dda-46ab-ab17-01c4e78d4094.png">

<img width="1166" alt="image" src="https://user-images.githubusercontent.com/170312/231087992-50ababfa-4939-449a-b276-85110de7dc6b.png">

<img width="1167" alt="image" src="https://user-images.githubusercontent.com/170312/231088742-f00a54a6-0db4-4a4b-82cb-b71a3c7f2105.png">

**Comment by Harikarthyk** [comment]
Completed

**Comment by wildone** [comment]
We need to have icon to match these states.

1. All component that support flow whould have a grayed out icon.
2. All component that have flow enable should have a colored icon.

Here is an example https://codepen.io/maxbarrass/pen/eYPWXoW

**Comment by Harikarthyk** [comment]
Completed.
