### ISSUE TITLE
In showcase page tab inside tab is not working.

### ISSUE THREAD

**Issue by rohitgupta274509** [typerefinery-ai/typerefinery-websight#324]
In showcase page of update in os-triage , when using tab inside a tab option then its not working as aspected. 

**To Reproduce**
1. Go to update page of incident management system.
2. Click on Enrichment tab.
3. When click on tab inside the enrichment tab its not working fine.

![image](https://user-images.githubusercontent.com/102787546/235438314-856c3e5d-c798-4098-b2f6-695d5877b463.png)

**Comment by wildone** [comment]
Any errors?
